site_name: Thoughts and Ramblings
site_description: Random ideas that may be helpful later
site_author: roemhildtg
site_url: http://roemhildtg.github.io

repo_url: http://github.com/roemhildtg/roemhildtg.github.io

docs_dir: '.'
